<?xml version="1.0" encoding="utf-8"?><Database Name="nxKTest_dev" Class="nxKTestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="ConnectionString" ConnectionString="Data Source=ENTERGATEDEV\SQLSERVER2008;Initial Catalog=nxKTest_dev;Persist Security Info=True;User ID=sa;Password=glas#3tape" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TestQuestion" Member="TestQuestions">
    <Type Name="TestQuestion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VirtualQuestion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QuestionSelectionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestQuestionSettingsId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TestQuestion_TestAnswerSetQuestion" Member="TestAnswerSetQuestions" ThisKey="Id" OtherKey="TestQuestionId" Type="TestAnswerSetQuestion" />
      <Association Name="QuestionSelection_TestQuestion" Member="QuestionSelection" ThisKey="QuestionSelectionId" OtherKey="Id" Type="QuestionSelection" IsForeignKey="true" />
      <Association Name="Question_TestQuestion" Member="Question" ThisKey="QuestionId" OtherKey="Id" Type="Question" IsForeignKey="true" />
      <Association Name="Test_TestQuestion" Member="Test" ThisKey="TestId" OtherKey="Id" Type="Test" IsForeignKey="true" />
      <Association Name="TestQuestionSetting_TestQuestion" Member="TestQuestionSetting" ThisKey="TestQuestionSettingsId" OtherKey="Id" Type="TestQuestionSetting" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionRights" Member="QuestionRights">
    <Type Name="QuestionRight">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdminUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Edit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="AdminUser_QuestionRight" Member="AdminUser" ThisKey="AdminUserId" OtherKey="Id" Type="AdminUser" IsForeignKey="true" />
      <Association Name="Question_QuestionRight" Member="Question" ThisKey="QuestionId" OtherKey="Id" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestAnswerBasic" Member="TestAnswerBasics">
    <Type Name="TestAnswerBasic">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestAnswerSetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestAnswerSetQuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastPassedForward" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QuestionAlternativeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="QuestionAlternative_TestAnswerBasic" Member="QuestionAlternative" ThisKey="QuestionAlternativeId" OtherKey="Id" Type="QuestionAlternative" IsForeignKey="true" />
      <Association Name="TestAnswerSet_TestAnswerBasic" Member="TestAnswerSet" ThisKey="TestAnswerSetId" OtherKey="Id" Type="TestAnswerSet" IsForeignKey="true" />
      <Association Name="TestAnswerSetQuestion_TestAnswerBasic" Member="TestAnswerSetQuestion" ThisKey="TestAnswerSetQuestionId" OtherKey="Id" Type="TestAnswerSetQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestAnswerImage" Member="TestAnswerImages">
    <Type Name="TestAnswerImage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestAnswerSetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestAnswerSetQuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionAlternativeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastPassedForward" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="X" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Y" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="QuestionAlternative_TestAnswerImage" Member="QuestionAlternative" ThisKey="QuestionAlternativeId" OtherKey="Id" Type="QuestionAlternative" IsForeignKey="true" />
      <Association Name="TestAnswerSet_TestAnswerImage" Member="TestAnswerSet" ThisKey="TestAnswerSetId" OtherKey="Id" Type="TestAnswerSet" IsForeignKey="true" />
      <Association Name="TestAnswerSetQuestion_TestAnswerImage" Member="TestAnswerSetQuestion" ThisKey="TestAnswerSetQuestionId" OtherKey="Id" Type="TestAnswerSetQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdminUser" Member="AdminUsers">
    <Type Name="AdminUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PublicId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="LicenseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CultureId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdminRoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PublicRoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsTemplate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="AdminUser_AdminUserInteractionRight" Member="AdminUserInteractionRights" ThisKey="Id" OtherKey="AdminUserId" Type="AdminUserInteractionRight" />
      <Association Name="AdminUser_AdminUserModule" Member="AdminUserModules" ThisKey="Id" OtherKey="AdminUserId" Type="AdminUserModule" />
      <Association Name="AdminUser_TestRight" Member="TestRights" ThisKey="Id" OtherKey="AdminUserId" Type="TestRight" />
      <Association Name="AdminUser_QuestionSelectionRight" Member="QuestionSelectionRights" ThisKey="Id" OtherKey="AdminUserId" Type="QuestionSelectionRight" />
      <Association Name="AdminUser_QuestionSelection" Member="QuestionSelections" ThisKey="Id" OtherKey="CreatorId" Type="QuestionSelection" />
      <Association Name="AdminUser_QuestionRight" Member="QuestionRights" ThisKey="Id" OtherKey="AdminUserId" Type="QuestionRight" />
      <Association Name="AdminUser_TestCorrector" Member="TestCorrectors" ThisKey="Id" OtherKey="AdminUserId" Type="TestCorrector" />
      <Association Name="AdminUser_PublicUserRight" Member="PublicUserRights" ThisKey="Id" OtherKey="AdminUserId" Type="PublicUserRight" />
      <Association Name="AdminUser_ImageRight" Member="ImageRights" ThisKey="Id" OtherKey="AdminUserId" Type="ImageRight" />
      <Association Name="AdminUser_Image" Member="Images" ThisKey="Id" OtherKey="OwnerId" Type="Image" />
      <Association Name="AdminUser_License" Member="Licenses" ThisKey="Id" OtherKey="CreatorId" Type="License" />
      <Association Name="AdminUser_Message" Member="Messages" ThisKey="Id" OtherKey="WriterId" Type="Message" />
      <Association Name="AdminUser_MessageAdminUser" Member="MessageAdminUsers" ThisKey="Id" OtherKey="AdminUserId" Type="MessageAdminUser" />
      <Association Name="AdminUser_Question" Member="Questions" ThisKey="Id" OtherKey="CreatorId" Type="Question" />
      <Association Name="AdminUser_MailText" Member="MailTexts" ThisKey="Id" OtherKey="CreatorId" Type="MailText" />
      <Association Name="AdminUser_Document" Member="Documents" ThisKey="Id" OtherKey="OwnerId" Type="Document" />
      <Association Name="AdminUser_DocumentRight" Member="DocumentRights" ThisKey="Id" OtherKey="AdminUserId" Type="DocumentRight" />
      <Association Name="AdminUser_Flash" Member="Flashes" ThisKey="Id" OtherKey="OwnerId" Type="Flash" />
      <Association Name="AdminUser_FlashRight" Member="FlashRights" ThisKey="Id" OtherKey="AdminUserId" Type="FlashRight" />
      <Association Name="AdminUser_Movie" Member="Movies" ThisKey="Id" OtherKey="OwnerId" Type="Movie" />
      <Association Name="AdminUser_MovieRight" Member="MovieRights" ThisKey="Id" OtherKey="AdminUserId" Type="MovieRight" />
      <Association Name="AdminUser_Sound" Member="Sounds" ThisKey="Id" OtherKey="OwnerId" Type="Sound" />
      <Association Name="AdminUser_SoundRight" Member="SoundRights" ThisKey="Id" OtherKey="AdminUserId" Type="SoundRight" />
      <Association Name="AdminUser_Test" Member="Tests" ThisKey="Id" OtherKey="CreatorId" Type="Test" />
      <Association Name="AdminUser_PublicUser" Member="PublicUser" Storage="_PublicUsers" ThisKey="Id" OtherKey="AdminUserId" Type="PublicUser" Cardinality="One" />
      <Association Name="AdminUser_PortalText" Member="PortalTexts" ThisKey="Id" OtherKey="CreatorId" Type="PortalText" />
      <Association Name="AdminUser_scormTest" Member="scormTests" ThisKey="Id" OtherKey="UserId" Type="scormTest" />
      <Association Name="AdminUser_QuestionSCOSetting" Member="QuestionSCOSettings" ThisKey="Id" OtherKey="UserId" Type="QuestionSCOSetting" />
      <Association Name="AdminUser_ErrorLog" Member="ErrorLogs" ThisKey="Id" OtherKey="AdminUserId" Type="ErrorLog" />
      <Association Name="License_AdminUser" Member="License" ThisKey="LicenseId" OtherKey="Id" Type="License" IsForeignKey="true" />
      <Association Name="Culture_AdminUser" Member="Culture" ThisKey="CultureId" OtherKey="Id" Type="Culture" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Question" Member="Questions">
    <Type Name="Question" Id="ID1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="QuestionTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QuestionSettingsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LatestChangeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QuestionText" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Imported" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ImportedId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PartialMatrixQuestionToQuestionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PartialMatrixQuestionSortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Question_TestQuestion" Member="TestQuestions" ThisKey="Id" OtherKey="QuestionId" Type="TestQuestion" />
      <Association Name="Question_QuestionSelectionQuestion" Member="QuestionSelectionQuestions" ThisKey="Id" OtherKey="QuestionId" Type="QuestionSelectionQuestion" />
      <Association Name="Question_QuestionRight" Member="QuestionRights" ThisKey="Id" OtherKey="QuestionId" Type="QuestionRight" />
      <Association Name="Question_ConditionalJumpQuestionCondition" Member="ConditionalJumpQuestionConditions" ThisKey="Id" OtherKey="QuestionId" Type="ConditionalJumpQuestionCondition" />
      <Association Name="Question_QuestionImage" Member="QuestionImages" ThisKey="Id" OtherKey="QuestionId" Type="QuestionImage" />
      <Association Name="Question_QuestionFeedback" Member="QuestionFeedbacks" ThisKey="Id" OtherKey="QuestionId" Type="QuestionFeedback" />
      <Association Name="Question_QuestionAlternative" Member="QuestionAlternatives" ThisKey="Id" OtherKey="QuestionId" Type="QuestionAlternative" />
      <Association Name="Question_Question" Member="Questions" ThisKey="Id" OtherKey="ParentId" Type="Question" />
      <Association Name="Question_TestAnswerMatrix" Member="TestAnswerMatrixes" ThisKey="Id" OtherKey="SupportQuestionId" Type="TestAnswerMatrix" />
      <Association Name="Question_TestAnswerSetQuestion" Member="TestAnswerSetQuestions" ThisKey="Id" OtherKey="QuestionId" Type="TestAnswerSetQuestion" />
      <Association Name="Question_QuestionSCOSetting" Member="QuestionSCOSettings" ThisKey="Id" OtherKey="QuestionId" Type="QuestionSCOSetting" />
      <Association Name="AdminUser_Question" Member="AdminUser" ThisKey="CreatorId" OtherKey="Id" Type="AdminUser" IsForeignKey="true" />
      <Association Name="Question_Question" Member="Parent" Storage="_Question1" ThisKey="ParentId" OtherKey="Id" Type="Question" IsForeignKey="true" />
      <Association Name="QuestionType_Question" Member="QuestionType" ThisKey="QuestionTypeId" OtherKey="Id" Type="QuestionType" IsForeignKey="true" />
      <Association Name="QuestionSetting_Question" Member="QuestionSetting" ThisKey="QuestionSettingsId" OtherKey="Id" Type="QuestionSetting" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestAnswerCombi" Member="TestAnswerCombis">
    <Type Name="TestAnswerCombi">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestAnswerSetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestAnswerSetQuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastPassedForward" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QuestionAlternativeDraggableId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuesitonAlternativeStaticId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="QuestionAlternative_TestAnswerCombi" Member="QuestionStaticAlternative" Storage="_QuestionAlternative" ThisKey="QuesitonAlternativeStaticId" OtherKey="Id" Type="QuestionAlternative" IsForeignKey="true" />
      <Association Name="QuestionAlternative_TestAnswerCombi1" Member="QuestionDraggableAlternative" Storage="_QuestionAlternative1" ThisKey="QuestionAlternativeDraggableId" OtherKey="Id" Type="QuestionAlternative" IsForeignKey="true" />
      <Association Name="TestAnswerSet_TestAnswerCombi" Member="TestAnswerSet" ThisKey="TestAnswerSetId" OtherKey="Id" Type="TestAnswerSet" IsForeignKey="true" />
      <Association Name="TestAnswerSetQuestion_TestAnswerCombi" Member="TestAnswerSetQuestion" ThisKey="TestAnswerSetQuestionId" OtherKey="Id" Type="TestAnswerSetQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestAnswerMatrix" Member="TestAnswerMatrixes">
    <Type Name="TestAnswerMatrix">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestAnswerSetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestAnswerSetQuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SupportQuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastPassedForward" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QuestionAlternativeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Question_TestAnswerMatrix" Member="Question" ThisKey="SupportQuestionId" OtherKey="Id" Type="Question" IsForeignKey="true" />
      <Association Name="QuestionAlternative_TestAnswerMatrix" Member="QuestionAlternative" ThisKey="QuestionAlternativeId" OtherKey="Id" Type="QuestionAlternative" IsForeignKey="true" />
      <Association Name="TestAnswerSet_TestAnswerMatrix" Member="TestAnswerSet" ThisKey="TestAnswerSetId" OtherKey="Id" Type="TestAnswerSet" IsForeignKey="true" />
      <Association Name="TestAnswerSetQuestion_TestAnswerMatrix" Member="TestAnswerSetQuestion" ThisKey="TestAnswerSetQuestionId" OtherKey="Id" Type="TestAnswerSetQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Test" Member="Tests">
    <Type Name="Test">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PublicId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="CreatorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TestTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestSettingsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestTextId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LatestChangeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RemovedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Test_TestRight" Member="TestRights" ThisKey="Id" OtherKey="TestId" Type="TestRight" />
      <Association Name="Test_TestQuestion" Member="TestQuestions" ThisKey="Id" OtherKey="TestId" Type="TestQuestion" />
      <Association Name="Test_TestCorrector" Member="TestCorrectors" ThisKey="Id" OtherKey="TestId" Type="TestCorrector" />
      <Association Name="Test_ConditionalJump" Member="ConditionalJumps" ThisKey="Id" OtherKey="TestId" Type="ConditionalJump" />
      <Association Name="Test_TestFeedback" Member="TestFeedbacks" ThisKey="Id" OtherKey="TestId" Type="TestFeedback" />
      <Association Name="Test_MailText" Member="MailTexts" ThisKey="Id" OtherKey="TestId" Type="MailText" />
      <Association Name="Test_TestReminderSetting" Member="TestReminderSettings" ThisKey="Id" OtherKey="TestId" Type="TestReminderSetting" />
      <Association Name="Test_Test" Member="Tests" ThisKey="Id" OtherKey="ParentId" Type="Test" />
      <Association Name="Test_PublicUserTest" Member="PublicUserTests" ThisKey="Id" OtherKey="TestId" Type="PublicUserTest" />
      <Association Name="Test_TestAnswerSet" Member="TestAnswerSets" ThisKey="Id" OtherKey="TestId" Type="TestAnswerSet" />
      <Association Name="AdminUser_Test" Member="AdminUser" ThisKey="CreatorId" OtherKey="Id" Type="AdminUser" IsForeignKey="true" />
      <Association Name="Test_Test" Member="Test1" ThisKey="ParentId" OtherKey="Id" Type="Test" IsForeignKey="true" />
      <Association Name="TestText_Test" Member="TestText" ThisKey="TestTextId" OtherKey="Id" Type="TestText" IsForeignKey="true" />
      <Association Name="TestType_Test" Member="TestType" ThisKey="TestTypeId" OtherKey="Id" Type="TestType" IsForeignKey="true" />
      <Association Name="TestSetting_Test" Member="TestSetting" ThisKey="TestSettingsId" OtherKey="Id" Type="TestSetting" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionSettings" Member="QuestionSettings">
    <Type Name="QuestionSetting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DefaultRequired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DefaultHideAlternativeFeedback" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RequiredMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequiredMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NeedsCorrecting" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DropDownDummy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RandomAlternativeOrder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Points" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PointsOnQuestionNotAlternatives" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PointsOnMatrixRowNotAlternatives" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShowFlags" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LeftFlag" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RightFlag" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UseSliderScale" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShowQuestionNameAsHeader" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="QuestionSetting_Question" Member="Questions" ThisKey="Id" OtherKey="QuestionSettingsId" Type="Question" />
    </Type>
  </Table>
  <Table Name="dbo.TestQuestionSettings" Member="TestQuestionSettings">
    <Type Name="TestQuestionSetting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Required" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HideAlternativeFeedback" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NrOfQuestionsInVirtualQuestion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TestQuestionSetting_TestQuestion" Member="TestQuestions" ThisKey="Id" OtherKey="TestQuestionSettingsId" Type="TestQuestion" />
    </Type>
  </Table>
  <Table Name="dbo.PublicUser" Member="PublicUsers">
    <Type Name="PublicUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PublicId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="LicenseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CultureId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PublicRoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AdminUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsFolder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StyleSheetId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PersonalNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HiddenIdentity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DatePortalLoginSent" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PublicUser_PublicUserInteractionRight" Member="PublicUserInteractionRights" ThisKey="Id" OtherKey="PublicUserId" Type="PublicUserInteractionRight" />
      <Association Name="PublicUser_PublicUserModule" Member="PublicUserModules" ThisKey="Id" OtherKey="PublicUserId" Type="PublicUserModule" />
      <Association Name="PublicUser_PublicUserRight" Member="PublicUserRights" ThisKey="Id" OtherKey="PublicUserId" Type="PublicUserRight" />
      <Association Name="PublicUser_PublicUserTest" Member="PublicUserTests" ThisKey="Id" OtherKey="PublicUserId" Type="PublicUserTest" />
      <Association Name="PublicUser_PublicUser" Member="PublicUsers" ThisKey="Id" OtherKey="ParentId" Type="PublicUser" />
      <Association Name="PublicUser_TestAnswerSet" Member="TestAnswerSets" ThisKey="Id" OtherKey="PublicUserId" Type="TestAnswerSet" />
      <Association Name="PublicUser_ErrorLog" Member="ErrorLogs" ThisKey="Id" OtherKey="PublicUserId" Type="ErrorLog" />
      <Association Name="AdminUser_PublicUser" Member="AdminUser" ThisKey="AdminUserId" OtherKey="Id" Type="AdminUser" IsForeignKey="true" />
      <Association Name="Culture_PublicUser" Member="Culture" ThisKey="CultureId" OtherKey="Id" Type="Culture" IsForeignKey="true" />
      <Association Name="License_PublicUser" Member="License" ThisKey="LicenseId" OtherKey="Id" Type="License" IsForeignKey="true" />
      <Association Name="PublicUser_PublicUser" Member="PublicUser1" ThisKey="ParentId" OtherKey="Id" Type="PublicUser" IsForeignKey="true" />
      <Association Name="StyleSheet_PublicUser" Member="StyleSheet" ThisKey="StyleSheetId" OtherKey="Id" Type="StyleSheet" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestSettings" Member="TestSettings">
    <Type Name="TestSetting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HasMultipleQuestionsPerPage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsPauseable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowsGoingBack" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowsPreviewQuestions" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasTimeLimit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TimeLimit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SaveAnswers" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasInfoPage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShowPartialResultAfterSubmit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RequiresLogin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaxNrOfAnswersPerUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CalculateMaxScoreOnSeenQuestionsOnly" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PreRequirementId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowTotalScoreWhileAnswering" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShowJournalWhileAnswering" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShowQuestionScoreWhileAnswering" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Anonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AlternativeId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MinNrOfAnswersForAverage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SendMailOnTestStart" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseSilverlightTimer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AllowPrintDiploma" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UseInstantFeedback" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InstantFeedbackDuration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShowMaxPointsOnQuestionWhileAnswering" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShowCorrectAnswerWhileAnswering" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShowCorrectAnswerInJournalAfterAnswered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SubmitScoreToScormTest" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ScormSuccessPercentage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TestSetting_Test" Member="Tests" ThisKey="Id" OtherKey="TestSettingsId" Type="Test" />
      <Association Name="TestFeedback_TestSetting" Member="PreRequirement" ThisKey="PreRequirementId" OtherKey="Id" Type="TestFeedback" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestAnswerSet" Member="TestAnswerSets">
    <Type Name="TestAnswerSet">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PublicId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PublicUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CompleteTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarkedForRemoval" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RemoveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsCompleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsPaused" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="WorkTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsImported" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MarkedForCorrecting" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CorrectedTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaxPossibleScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NotFinishedInTime" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TimeLeftLastPage" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastPageEntered" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScormUserId" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ScormFirstName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ScormLastName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="TestAnswerSet_TestAnswerText" Member="TestAnswerTexts" ThisKey="Id" OtherKey="TestAnswerSetId" Type="TestAnswerText" />
      <Association Name="TestAnswerSet_TestAnswerBasic" Member="TestAnswerBasics" ThisKey="Id" OtherKey="TestAnswerSetId" Type="TestAnswerBasic" />
      <Association Name="TestAnswerSet_TestAnswerSetJump" Member="TestAnswerSetJumps" ThisKey="Id" OtherKey="TestAnswerSetId" Type="TestAnswerSetJump" />
      <Association Name="TestAnswerSet_TestAnswerImage" Member="TestAnswerImages" ThisKey="Id" OtherKey="TestAnswerSetId" Type="TestAnswerImage" />
      <Association Name="TestAnswerSet_TestAnswerCombi" Member="TestAnswerCombis" ThisKey="Id" OtherKey="TestAnswerSetId" Type="TestAnswerCombi" />
      <Association Name="TestAnswerSet_TestAnswerMatrix" Member="TestAnswerMatrixes" ThisKey="Id" OtherKey="TestAnswerSetId" Type="TestAnswerMatrix" />
      <Association Name="TestAnswerSet_TestAnswerSetQuestion" Member="TestAnswerSetQuestions" ThisKey="Id" OtherKey="TestAnswerSetId" Type="TestAnswerSetQuestion" />
      <Association Name="PublicUser_TestAnswerSet" Member="PublicUser" ThisKey="PublicUserId" OtherKey="Id" Type="PublicUser" IsForeignKey="true" />
      <Association Name="Test_TestAnswerSet" Member="Test" ThisKey="TestId" OtherKey="Id" Type="Test" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestAnswerSetQuestion" Member="TestAnswerSetQuestions">
    <Type Name="TestAnswerSetQuestion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestAnswerSetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestQuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxPossibleScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LatestChangeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WorkTimeSeconds" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnsweredCorrectly" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TestAnswerSetQuestion_TestAnswerText" Member="TestAnswerTexts" ThisKey="Id" OtherKey="TestAnswerSetQuestionId" Type="TestAnswerText" />
      <Association Name="TestAnswerSetQuestion_TestAnswerBasic" Member="TestAnswerBasics" ThisKey="Id" OtherKey="TestAnswerSetQuestionId" Type="TestAnswerBasic" />
      <Association Name="TestAnswerSetQuestion_TestAnswerImage" Member="TestAnswerImages" ThisKey="Id" OtherKey="TestAnswerSetQuestionId" Type="TestAnswerImage" />
      <Association Name="TestAnswerSetQuestion_TestAnswerCombi" Member="TestAnswerCombis" ThisKey="Id" OtherKey="TestAnswerSetQuestionId" Type="TestAnswerCombi" />
      <Association Name="TestAnswerSetQuestion_TestAnswerMatrix" Member="TestAnswerMatrixes" ThisKey="Id" OtherKey="TestAnswerSetQuestionId" Type="TestAnswerMatrix" />
      <Association Name="TestAnswerSetQuestion_TestAnswerSetSCOQuestion" Member="TestAnswerSetSCOQuestions" ThisKey="Id" OtherKey="TestAnswerSetQuestionId" Type="TestAnswerSetSCOQuestion" />
      <Association Name="Question_TestAnswerSetQuestion" Member="Question" ThisKey="QuestionId" OtherKey="Id" Type="Question" IsForeignKey="true" />
      <Association Name="TestAnswerSet_TestAnswerSetQuestion" Member="TestAnswerSet" ThisKey="TestAnswerSetId" OtherKey="Id" Type="TestAnswerSet" IsForeignKey="true" />
      <Association Name="TestQuestion_TestAnswerSetQuestion" Member="TestQuestion" ThisKey="TestQuestionId" OtherKey="Id" Type="TestQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.scormTests" Member="scormTests">
    <Type Name="scormTest">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FolderId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="scormIdentifier" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="AdminUser_scormTest" Member="AdminUser" ThisKey="UserId" OtherKey="Id" Type="AdminUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionSCOSettings" Member="QuestionSCOSettings">
    <Type Name="QuestionSCOSetting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FolderId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntryPoint" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AdminUser_QuestionSCOSetting" Member="AdminUser" ThisKey="UserId" OtherKey="Id" Type="AdminUser" IsForeignKey="true" />
      <Association Name="Question_QuestionSCOSetting" Member="Question" ThisKey="QuestionId" OtherKey="Id" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestAnswerSetSCOQuestion" Member="TestAnswerSetSCOQuestions">
    <Type Name="TestAnswerSetSCOQuestion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestAnswerSetQuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="score_raw" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="sucess_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="completion_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="score_scaled" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="score_max" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="score_min" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="session_time_seconds" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TestAnswerSetQuestion_TestAnswerSetSCOQuestion" Member="TestAnswerSetQuestion" ThisKey="TestAnswerSetQuestionId" OtherKey="Id" Type="TestAnswerSetQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.AdminUser_GetVisibleRootQuestions_ByAdminUserId" Method="AdminUser_GetVisibleRootQuestions_ByAdminUserId">
    <Parameter Name="adminUserId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>