alias vi=vim
alias info="info --vi-keys"
alias what="whatis"
alias octave="octave -q"
alias ping="ping -c 3"
alias ll="ls -ls"
alias killt="kill -s SIGTERM"
alias mp="mpc play"
alias ms="mpc pause"
alias javac="javac -Xlint"
alias mv="mv -i"
alias cp="cp -i"
alias date="date --rfc-3339=second"
alias mpcu="mpc volume +10"
alias mpcd="mpc volume -10"
alias unzipl="unzip -l"
alias format="uncrustify -c ~/.kr-indent.cfg --replace --no-backup "
alias ftpeis="ftp eishalmstad.dyndns.org"
alias ssheis="ssh albert@eishalmstad.dyndns.org"
alias mymake="make --silent -f ~/workspace/c/Makefile -C ."
alias mymakec="make --silent -f ~/workspace/c/Makefile -C . clean"
alias myghc="ghc --make -outputdir obj -o a.out"
alias myant="ant -f ~/workspace/java/build.xml -Dbasedir=${PWD}"
